# Generated by Django 4.0.4 on 2022-06-09 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together={('title', 'author')},
        ),
    ]
