# Generated by Django 4.0.4 on 2022-06-07 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icann', models.CharField(blank=True, max_length=7, null=True)),
                ('isd', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('city_town', models.CharField(blank=True, max_length=50, null=True)),
                ('district_county', models.CharField(blank=True, max_length=50, null=True)),
                ('state_province', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationapp.countrymodel')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('-created_at',),
                'unique_together': {('city_town', 'district_county', 'state_province', 'country')},
            },
        ),
    ]
