# Generated by Django 4.0.4 on 2022-06-10 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Default Country Name', help_text='Common name of the country.', max_length=50, unique=True)),
                ('official_name', models.CharField(blank=True, help_text='Official name of the country as presented in legal documents.', max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, help_text='Slug used to identify/route to the country.', max_length=128, null=True)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-3 country code.', max_length=10, null=True)),
                ('country_region', models.CharField(blank=True, help_text='Region of the country.', max_length=128, null=True)),
                ('internet_tld', models.CharField(blank=True, help_text='Internet top level domain for the country', max_length=10, null=True)),
                ('calling_code', models.CharField(blank=True, help_text='International Dialing Code for the country.', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('city_town', models.CharField(blank=True, max_length=50, null=True)),
                ('district_county', models.CharField(blank=True, max_length=50, null=True)),
                ('state_province', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationapp.countrymodel')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('country', 'city_town'),
                'unique_together': {('city_town', 'district_county', 'state_province', 'country')},
            },
        ),
    ]
