# Generated by Django 4.0.4 on 2022-06-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymodel',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-3 country code.', max_length=5, null=True),
        ),
    ]
