# Generated by Django 4.0.4 on 2022-06-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0003_alter_locationmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
