# Generated by Django 4.0.4 on 2022-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0003_countrymodel_country_region_alter_countrymodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='name',
            field=models.CharField(default='Default Country Name', help_text='Common name of the country.', max_length=50, unique=True),
        ),
    ]
