# Generated by Django 4.0.4 on 2022-06-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0004_alter_locationmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymodel',
            name='common_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
