# Generated by Django 4.0.4 on 2022-06-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0004_alter_countrymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='calling_code',
            field=models.CharField(blank=True, help_text='International Dialing Code for the country.', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-3 country code.', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug used to identify/route to the country.', max_length=128, null=True),
        ),
    ]
