# Generated by Django 4.0.4 on 2022-06-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0005_alter_countrymodel_calling_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='calling_code',
            field=models.CharField(blank=True, help_text='International Dialing Code for the country.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-3 country code.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='internet_tld',
            field=models.CharField(blank=True, help_text='Internet top level domain for the country', max_length=10, null=True),
        ),
    ]
