# Generated by Django 4.0.4 on 2022-06-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined', 'id'), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
