# Generated by Django 4.0.4 on 2022-06-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/defaults/profile_picture.png', upload_to='images/profile_pictures/'),
        ),
    ]
