# Generated by Django 4.0.5 on 2022-06-15 15:31

import django.core.validators
from django.db import migrations, models
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(code='invalid_email', message='Please enter a valid email address.')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blacklisted Email',
                'verbose_name_plural': 'Blacklisted Emails',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='BlacklistedPhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Please enter a valid phone number.', regex=re.compile('^[0-9]{10}$'))])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blacklisted Phone Number',
                'verbose_name_plural': 'Blacklisted Phone Numbers',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='BlacklistedPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('plaintext_password', models.CharField(max_length=128, unique=True)),
                ('hashed_value', models.CharField(blank=True, max_length=256, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blacklisted Password',
                'verbose_name_plural': 'Blacklisted Passwords',
                'ordering': ('-date_added',),
                'unique_together': {('plaintext_password', 'hashed_value')},
            },
        ),
    ]
